server {
    listen       8080;
    listen  [::]:8080;
    server_name  _;

    root   /usr/share/nginx/html;
    index  index.html;

    # Assets hashés par Angular : long cache
    location ~* \.(?:js|css|woff2?|ttf|eot|svg|png|jpg|jpeg|gif|ico|webp|avif)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    # SPA fallback : toute route inconnue renvoie index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Health-check conteneur
    location = /healthz {
        access_log off;
        add_header Content-Type text/plain;
        return 200 "ok";
    }
}
